apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-dns-issuer"
spec:
  rules:
  - host: eks-project.lab.abdirahman-ismail.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80

  tls:
  - hosts:
    - eks-project.lab.abdirahman-ismail.com
    secretName: wildcard-lab-abdirahman-ismail-com-tls
