apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-lab-abdirahman-ismail-com
spec:
  secretName: wildcard-lab-abdirahman-ismail-com-tls
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
  dnsNames:
  - '*.eks-project.lab.abdirahman-ismail.com'
  - 'eks-project.lab.abdirahman-ismail.com'
